language: generic
sudo: required
services:
 - docker


before_install:
 - docker build -t bagesh456/docker-react -f Dockerfile.dev .

script:
 - docker run -e CI=true bagesh456/docker-react npm run test
